filetype off
set rtp+=$GITHUB_WORKSPACE/vader.vim
let &rtp.=','.expand('%:p:h')
set shiftwidth=2
set backspace=2
set tabstop=2
set softtabstop=2
set expandtab
filetype plugin indent on
syntax enable
set nomore
set noswapfile

